import React from "react";
import { jsPDF } from "jspdf";

const PdfGenerator = () => {
  const generatePdf = () => {
    const doc = new jsPDF();

    // Add Header
    doc.setFont("helvetica", "bold"); // Bold font
    doc.setFontSize(18);
    doc.setTextColor(0, 102, 204); // Blue color
    doc.text("Exercise 01", 105, 20, { align: "center" }); // Centered header

    // Add an image to the header (optional)
    // Example: Base64 or URL image
    const imgUrl = "https://picsum.photos/200";
    const img = new Image();
    img.src = imgUrl;
    img.onload = () => {
      doc.addImage(img, "JPEG", 10, 25, 40, 40); // Image on the top left

      // Add Body
      doc.setFont("times", "normal");
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0); // Black color
      const bodyText =
        "This is the body of the PDF. You can add paragraphs of text here. Use this section for detailed content or explanations.";
      doc.text(bodyText, 10, 80, { maxWidth: 190 });

      // Add Footer
      doc.setFont("courier", "italic");
      doc.setFontSize(10);
      doc.setTextColor(128, 128, 128); // Gray color
      doc.text("Generated by Gravitorix", 105, 290, { align: "center" }); // Footer at the bottom center

      // Save the PDF
      doc.save("styled_document.pdf");
    };
  };

  return (
    <div>
      <button onClick={generatePdf}>Download PDF</button>
    </div>
  );
};

export default PdfGenerator;
